# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-04 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_doctor_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activityDetails',
            new_name='Activity_Details',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='timeStamp',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='blood_Type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='height',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='weight',
            field=models.CharField(default='', max_length=3),
        ),
    ]
