# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-05 20:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170304_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'permissions': (('view_medical', 'can view medical'), ('edit_medical', 'can edit medical'))},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
